fgmacedo/python-statemachine

.checkignore
.coveragerc
.travis.yml
HISTORY.rst
requirements_test.txt
statemachine/statemachine.py
tests/conftest.py
tests/test_callable_instance.py
tests/test_multiple_destinations.py
tests/test_statemachine.py
tests/test_transitions.py

This PR aims to add two main features:
The syntax:
``` python
from datetime import datetime
from statemachine import StateMachine, State
class ApprovalMachine(StateMachine):
requested = State('Requested', initial=True)
accepted = State('Accepted')
rejected = State('Rejected')
completed = State('Completed')
@requested.to(accepted, rejected)
def validate(self, *args, **kwargs):
if self.model.is_ok():
self.model.accepted_at = datetime.now()
return self.model, self.accepted
else:
self.model.rejected_at = datetime.now()
return self.model, self.rejected
@accepted.to(completed)
def complete(self):
self.model.completed_at = datetime.now()
@requested.to(requested)
def update(self, **kwargs):
for k, v in kwargs.items():
setattr(self.model, k, v)
return self.model
@rejected.to(requested)
def …
```

Feature/transition to multiple states / transition as decorator

---

statemachine/registry.py
tests/test_registry.py

In order to avoid circular imports between a statemachine and a Django module, this PR leverages the use of Django `autodiscover_modules` feature. Allowing a lazy load of `statemachine` or `statemachines` modules when they are requested using the mixin/registry feature.

Registry auto discovering statemachine modules if in a Django project

---

statemachine/registry.py
tests/test_registry.py

Fix a bug when using mixin with the Django registry not loading modules on Django1.7+.

Fix registry loading modules for django 1.7+

---

setup.py

Closes #166 with explicit encoding of `utf-8` when reading README and HISTORY files due to non-ascii chars on examples.
To reproduce, try to build a docker image with: 
``` Dockerfile
FROM ubuntu:16.04
RUN apt-get update \
&& apt-get install -y python3 python3-pip
COPY ./setup.py ./setup.cfg ./README.rst ./HISTORY.rst /statemachine/
COPY ./docs /statemachine/docs
COPY ./tests/ /statemachine/tests
COPY ./statemachine /statemachine/statemachine
WORKDIR /statemachine
RUN pip3 install -e .
```

fix(setup) fix install on Dockerfile without explicit locale closes #166

---

.gitignore
AUTHORS.rst
statemachine/statemachine.py
tests/test_statemachine.py
tests/test_transitions.py

Validate Statemachine to have only one component

---

HISTORY.rst
README.rst
statemachine/statemachine.py
tests/conftest.py
tests/test_transitions.py

Original idea from by @romulorosa (Closes #84).
This PR implements a reverse transition. The feature allow us to write a simpler code in situations which you have multiple source transitions to a unique destination, such as: 
``` python
class MyTransactionStateMachine(StateMachine):
[...]
cancel = (
initiated.to(cancelled) |
waiting_approval.to(cancelled) |
in_progress.to(cancelled) |
suspended.to(cancelled)            
)
```
Using `from_` you are able to write a code similar to:
``` python
class MyTransactionStateMachine(StateMachine):
[...]
cancel = cancelled.from_(
initiated, 
waiting_approval,  
in_progress, 
suspended
)
```

Add support for reverse transtitions

---

HISTORY.rst
statemachine/statemachine.py
tests/test_state_callbacks.py

Fix current state equal to destination on enter events.

---

statemachine/statemachine.py
tests/test_statemachine.py

fix state value misjudged when state value is an "boolean False value" rather than None

fix state value misjudged when state value is an "boolean False value"

---

statemachine/statemachine.py
tests/test_statemachine_bounded_transitions.py

Add args to the bounded transitions "on_enter_*", "on_exit_*", to add more logic on state machine transitions, that will allow us to use the same args used to make the transition on the bounded transitions as well.

chore: add args to bounded transitions

---

README.rst
statemachine/statemachine.py
tests/conftest.py
tests/test_statemachine.py
tests/test_transitions.py

Add a feature to explicitly define which states are final states.
This requires avoiding transitions coming from final states and also makes it possible to list all final states of an FSM.
The Java Spring-statemachine is an example of FSM implementation which allow final states definition:
https://docs.spring.io/spring-statemachine/docs/current/reference/#statemachine-config-states
```
...
.withStates()
.initial(States.S1)
.end(States.SF) // Final State definition
.states(EnumSet.allOf(States.class));
...
```

Feat: Add final states

---

README.rst
statemachine/exceptions.py
statemachine/graph.py
statemachine/statemachine.py
statemachine/utils.py
tests/conftest.py
tests/test_multiple_destinations.py
tests/test_statemachine.py
tests/test_statemachine_inheritance.py
tests/test_transitions.py
tox.ini

Adding conditions support.
Fixes #286 
Closes #243
This allows usage like this:
``` python
class ApprovalMachine(StateMachine):
"A workflow"
requested = State('Requested', initial=True)
accepted = State('Accepted')
rejected = State('Rejected')
completed = State('Completed')
validate = (
requested.to(accepted, conditions="is_ok") |
requested.to(rejected) |
accepted.to(completed)
)
retry = rejected.to(requested)
def on_validate(self):
if self.is_accepted and self.model.is_ok():
return 'congrats!'
```
Where `is_ok` may be a property or method on the `machine` or in the `model`.

chore: Adding conditions support

---

.flake8
docs/conf.py
setup.py
statemachine/callable_proxy.py
statemachine/event.py
statemachine/event_data.py
statemachine/model.py
statemachine/registry.py
statemachine/state.py
statemachine/statemachine.py
statemachine/transition.py
statemachine/transition_list.py
statemachine/utils.py
tests/examples/order_control_machine.py
tests/test_actions.py
tests/test_callable_instance.py
tests/test_callbacks.py
tests/test_multiple_destinations.py
tests/test_statemachine.py
tests/test_statemachine_bounded_transitions.py
tests/test_transitions.py

Extract code to medicated modules.
The main module `statemachine.py` was huge, extracting each class to its own module.

refac: Extract code to medicated modules

---

statemachine/transition_list.py
tests/test_transition_list.py

Fix `TransitionList.__or__` mutating itself instead of returning a new instance. 
Closes #308.

Fix TransitionList.__or__ mutating itself instead of returning a new instance. Closes #308.

---

docs/diagram.md
statemachine/contrib/diagram.py
tests/test_contrib_diagram.py

Generate a `StateMachine` diagram from the command line.
```bash
❯ python -m statemachine.contrib.diagram --help
usage: diagram.py [OPTION] <classpath> <out>
Generate diagrams for StateMachine classes.
positional arguments:
classpath   A fully-qualified dotted path to the StateMachine class.
out         File to generate the image using extension as the output format.
optional arguments:
-h, --help  show this help message and exit
```
```
python -m statemachine.contrib.diagram tests.examples.guess_the_number_machine.GuessTheNumberMachine number.pdf
```
[number.pdf](https://github.com/fgmacedo/python-statemachine/files/10394149/number.pdf)
``` bash
python -m statemachine.contrib.diagram tests.examples.guess_the_number_machine.GuessTheNumberMachine number.png
```

feat: Generate StateMachine diagram from cmd line

---

README.rst
docs/actions.md
docs/index.rst
docs/observers.md
docs/releases/1.0.0.md
statemachine/callbacks.py
statemachine/contrib/diagram.py
statemachine/dispatcher.py
statemachine/factory.py
statemachine/state.py
statemachine/statemachine.py
statemachine/transition.py
tests/test_observer.py

StateMachine now supports adding observers to a running instance using `StateMachine.add_observer`.
Observers are a way to generically add behavior to a StateMachine without changing its internal implementation.
One possible use case is to add an observer that prints a log message when the SM runs a transition or enters a new state.
Giving the `traffic_light_machine.py` as example:
```py
>>> from tests.examples.traffic_light_machine import TrafficLightMachine
>>> class LogObserver(object):
...     def __init__(self, name):
...         self.name = name
...
...     def after_transition(self, event, source, target):
...         print("{} after: {}--({})-->{}".format(self.name, source.id, event, target.id))
...
...     def on_enter_state(self, target, event):
...         print("{} enter: {} …
```

feat: StateMachine observers

---

statemachine/dispatcher.py
tox.ini

Fixes usage of `inspect.getargspec` that was removed on python 3.11. Closes #316

fix: inspect.getargspec removed on 3.11. Closes #316

---

docs/releases/2.0.0.md
statemachine/dispatcher.py
statemachine/signature.py
tests/test_dispatcher_methodcaller.py
tests/test_signature.py

- [Closes #341](https://github.com/fgmacedo/python-statemachine/issues/341): Fix dynamic dispatch on methods with default parameters.

fix: Signature adapter

---

.github/workflows/python-package.yml
tests/conftest.py
tests/test_signature.py
tests/test_signature_positional_only.py

Due to a cache-key error, we're restoring and running the tests against the last updated virtualenv. This was causing random errors on the `test_signature.py` test that only exists on Python3.8+ when running on the python3.7 venv.
Since there's no way to conditionally ignore `SyntaxError` as the module is not importable (https://github.com/pytest-dev/pytest/issues/2817), we've isolated the 3.8+ tests on its own module that is not ignored when running the 3.7 suite.

fix: Test matrix python version not being cached properly

---

docs/releases/2.0.0.md
statemachine/factory.py
statemachine/statemachine.py
tests/test_statemachine.py

Closes https://github.com/fgmacedo/python-statemachine/issues/350
`StateMachine` now can now be subclassed with abstract classes (ones that do not define states or transitions). Abstract StateMachines cannot be instantiated.

feat: Support abstract SM classes. Closes #350

---

docs/actions.md
docs/releases/2.0.0.md
statemachine/dispatcher.py
statemachine/event.py
statemachine/event_data.py
statemachine/statemachine.py
statemachine/transition.py
tests/examples/order_control_rich_model_machine.py
tests/test_transitions.py

Allows the usage of `events` on callbacks.
```py
class ChainedSM(StateMachine):
a = State(initial=True)
b = State()
c = State()
t1 = a.to(b, after="t1") | b.to(c)
```
Closes: https://github.com/fgmacedo/python-statemachine/issues/351

feat: Allow using events on callbacks

---

docs/contributing.md
docs/releases/2.0.0.md
statemachine/callbacks.py
statemachine/dispatcher.py
statemachine/exceptions.py
statemachine/factory.py
statemachine/i18n.py
statemachine/locale/en/LC_MESSAGES/statemachine.po
statemachine/locale/pt_BR/LC_MESSAGES/statemachine.po
statemachine/state.py
statemachine/statemachine.py
statemachine/utils.py

Add support for internationalization, translating the messages into `pt_BR` as an example.
Extract a `Portable Object Template` (`POT`) file:
```shell
pybabel extract statemachine -o statemachine/locale/statemachine.pot
```
Then, copy the template as a `.po` file into the target locale folder. For example, if you're adding support for Brazilian Portuguese language, the code is `pt_BR`, and the file path should be `statemachine/locale/pt_BR/LC_MESSAGES/statemachine.po`:
```shell
cp statemachine/locale/statemachine.pot statemachine/locale/pt_BR/LC_MESSAGES/statemachine.po
```
Then open the `statemachine.po` and translate.
After translation, to get the new language working locally, you need to compile the `.po` files into `.mo`  (binary format). Run:
```shell
pybabel compile -d …
```

feat: Add i18n support. Closes #19

---

README.md
docs/actions.md
docs/api.md
docs/diagram.md
docs/guards.md
docs/index.md
docs/integrations.md
docs/mixins.md
docs/models.md
docs/releases/1.0.1.md
docs/releases/1.0.3.md
docs/releases/2.0.0.md
docs/states.md
docs/transitions.md
statemachine/event.py
statemachine/event_data.py
statemachine/exceptions.py
statemachine/state.py
statemachine/statemachine.py
tests/examples/order_control_rich_model_machine.py
tests/examples/persistent_model_machine.py
tests/test_transitions.py

You can now instantiate a {ref}`StateMachine` with `allow_event_without_transition=True`,
so the state machine will allow triggering events that may not lead to a state {ref}`transition`,
including tolerance to unknown {ref}`event` triggers.
The default value is ``False``, that keeps the backward compatible behavior of when an
event does not result in a {ref}`transition`, an exception ``TransitionNotAllowed`` will be raised.
```py
>>> from statemachine import StateMachine, State
>>> class ApprovalMachine(StateMachine):
...     pending = State(initial=True)
...     waiting_approval = State()
...     approved = State(final=True)
...
...     start = pending.to(waiting_approval)
...     approve = waiting_approval.to(approved)
...
>>> sm = ApprovalMachine(allow_event_without_transition=True) …
```

feat: allow_event_without_transition

---

docs/releases/2.0.0.md
docs/transitions.md
statemachine/callbacks.py
statemachine/event.py
statemachine/transition.py
tests/examples/traffic_light_machine.py
tests/test_events.py
tests/testcases/issue308.md

Given this state machine:
```py
from statemachine import State
from statemachine import StateMachine
class TrafficLightMachine(StateMachine):
"A traffic light machine"
green = State(initial=True)
yellow = State()
red = State()
slowdown = green.to(yellow)
stop = yellow.to(red)
go = red.to(green)
cycle = slowdown | stop | go
def before_slowdown(self):
print("Slowdown")
def before_cycle(self, event: str, source: State, target: State):
return f"Running {event} from {source.id} to {target.id}"
```
Note that the state machine definition is sharing the same instance of transitions between two events. Like this:
Running this SM without the fix, when sending the event `cycle`, the `slowdown` action was also called:
```python
>>> sm = TrafficLightMachine()
>>> sm.send("cycle")
'Slowdown'
['Running …
```

fix: Transition with multiple events was calling actions of all events

---

docs/releases/2.0.1.md
docs/releases/index.md
statemachine/signature.py
tests/test_signature.py

Add support for wrapping functools.partial. Closes #369.

fix: Add support for wrapping functools.partial. Closes #369

---

docs/releases/2.1.0.md
statemachine/callbacks.py
statemachine/dispatcher.py
tests/test_dispatcher.py
tests/testcases/issue384_multiple_observers.md

Fixes #384 .
we register multiple observers to the same named callback.
This works also as a regression test.
```py
>>> from statemachine import State
>>> from statemachine import StateMachine
>>> class MyObs:
...     def on_move_car(self):
...         print("I observed moving from 1")
>>> class MyObs2:
...     def on_move_car(self):
...         print("I observed moving from 2")
...
>>> class Car(StateMachine):
...     stopped = State(initial=True)
...     moving = State()
...
...     move_car = stopped.to(moving)
...     stop_car = moving.to(stopped)
...
...     def on_move_car(self):
...         print("I'm moving")
```
Running:
```py
>>> car = Car()
>>> obs = MyObs()
>>> obs2 = MyObs2()
>>> car.add_observer(obs)
Car(model=Model(state=stopped), state_field='state', …
```

fix: Multiple observers can watch the same callback

---

docs/releases/2.1.1.md
docs/releases/index.md
poetry.lock
pyproject.toml
statemachine/signature.py
tests/test_mock_compatibility.py

Fixes #391 .
Changed `SignatureAdapter` class to fix a bug where `cls.from_callable(method)` would return a `Signature` object instead of a `SignatureAdapter` if the method already had a `Signature`. Ensures that `cls.from_callable(method)` always returns a `SignatureAdapter`.

fix: Add support for pytest-mock spy method fixing the SignatureAdapter

---

statemachine/factory.py
tests/test_statemachine.py

Improve type hints as pointed out on https://github.com/fgmacedo/python-statemachine/issues/398.
Closes https://github.com/fgmacedo/python-statemachine/issues/398.

chore: Improved factory type hints

---

docs/states.md
docs/transitions.md
statemachine/factory.py
statemachine/statemachine.py
tests/conftest.py
tests/test_callbacks.py
tests/test_multiple_destinations.py
tests/test_rtc.py
tests/test_statemachine.py
tests/test_statemachine_bounded_transitions.py
tests/test_statemachine_inheritance.py
tests/test_transitions.py
tests/testcases/issue406.md

Implements ideas in #408, by adding checks for states with no outgoing transitions (`_check_trap_states`) and states that have no path to a final state, if final states exist (`_check_reachable_final_states`).
It will generate a warning if `strict_states=False`, and an an exception if `strict_states=True`. The current default is False, but i have updated all the tests to pass with the default set to True.
This is a first pass at the code, please give me some feedback before i start writing up the documentation.

Check for trap states and states that can't reach a final state

---

statemachine/callbacks.py
statemachine/statemachine.py
tests/test_deepcopy.py

Fixes #424.
As declared on the related issue:
> The MachineMixin for Django seems to behave differently when models are used within django tests.
> Oddly enough, any objects created during setUpTestData seem to cause transitions to bypass checks like
conditions.
The root cause of the issue lies in the setUpTestData() method. Every cls attr created in this method is wrapped in a [TestData](https://github.com/django/django/blob/f0d50a937910571fc4adb7e6fb91045cdc215aa8/django/test/testcases.py#L1298-L1333) class, which performs a deepcopy() for each test, so this is designed to allow safe alteration of objects between tests on the same TestCase instance.
However, this conflicts with the creation strategy of state machines. The references of properties/methods used as actions/conditions are …

Reconstructing callable references when using deepcopy over a SM.

---

statemachine/dispatcher.py
statemachine/signature.py
statemachine/state.py
statemachine/statemachine.py
statemachine/transition.py
tests/examples/order_control_rich_model_machine.py
tests/test_callbacks.py
tests/test_dispatcher.py
tests/test_transition_list.py
tests/testcases/issue417.md

fix: Fix passing conditions callbacks as references.

---

docs/authors.md
statemachine/utils.py
tests/test_deepcopy.py
tests/test_statemachine.py
tests/test_threading.py

Based on the work on https://github.com/fgmacedo/python-statemachine/pull/444
Thanks @jsbueno for the huge help here!
Closes: https://github.com/fgmacedo/python-statemachine/issues/443

Fix regression with asyncio and threading

---

docs/processing_model.md
docs/releases/1.0.1.md
docs/releases/2.3.2.md
statemachine/event.py
statemachine/event_data.py
statemachine/statemachine.py
tests/testcases/issue449.md

- chore: Processing block protected by a threading.Lock
- fix: Regression that did not trigger events in nested calls within an already running transition. Closes #449

Fix regression that did not trigger events in nested calls within an already running transition

---

docs/releases/2.3.2.md
statemachine/signature.py
tests/conftest.py
tests/django_project/core/settings.py
tests/django_project/workflow/tests.py

CLoses #446 .
I've added a `sync_to_async` wrap around sync callbacks if `asgiref` is available, as pointed out [in Django's async safety docs](https://docs.djangoproject.com/en/5.1/topics/async/#async-safety).

fix: Regression that broke sync callbacks interacting with Django ORM. Closes #446

---

docs/mixins.md
docs/releases/2.3.2.md
statemachine/mixins.py
statemachine/statemachine.py
statemachine/states.py
tests/django_project/workflow/models.py
tests/django_project/workflow/statemachines.py
tests/django_project/workflow/tests.py
tests/examples/enum_campaign_machine.py
tests/examples/user_machine.py
tests/test_statemachine.py

Now it's possible to bind events to external objets. One expected use case is in conjunction with the {ref}`Mixins` models,
that wrap state machines internally. This way you don't need to expose the state machine.

chore: Improved enum support; Allow binding eventes to objects

---

statemachine/contrib/diagram.py

Closes: https://github.com/fgmacedo/python-statemachine/issues/469

fix: Removing unit from fontsize when calling pydot

---

.github/workflows/python-package.yml
.pre-commit-config.yaml
docs/contributing.md

Missing pre-commit and docs from the previous work on https://github.com/fgmacedo/python-statemachine/pull/491.

chore: Fix pre-commit and update docs references for Poetry to UV

---

statemachine/callbacks.py
statemachine/statemachine.py

Improved support for pickle: https://github.com/fgmacedo/python-statemachine/discussions/499#discussion-7532641
Refac of #500 using `__getstate__` and `__setstate__` for both pickle and deepcopy.

refac: Improved support for pickle and deepcopy

---

statemachine/engines/base.py
statemachine/event.py
statemachine/events.py
statemachine/transition_list.py
statemachine/transition_mixin.py
tests/test_events.py

Allows using the same constructs on `Event` as in the `TransitionList` for registering callbacks using the decorator syntax.
Relates to #503 as a desired addition.

feat: Allow using event as decorator to register callbacks

---

docs/guards.md
docs/releases/2.5.0.md
docs/releases/index.md
pyproject.toml
statemachine/spec_parser.py
statemachine/state.py
tests/examples/lor_machine.py
tests/test_spec_parser.py
uv.lock

Adds support for comparison operators into {ref}`Condition expressions`.
The following comparison operators are supported:
1. `>` — Greather than.
2. `>=` — Greather than or equal.
3. `==` — Equal.
4. `!=` — Not equal.
5. `<` — Lower than.
6. `<=` — Lower than or equal.
Example:
```py
>>> from statemachine import StateMachine, State, Event
>>> class AnyConditionSM(StateMachine):
...     start = State(initial=True)
...     end = State(final=True)
...
...     submit = Event(
...         start.to(end, cond="order_value > 100"),
...         name="finish order",
...     )
...
...     order_value: float = 0
>>> sm = AnyConditionSM()
>>> sm.submit()
Traceback (most recent call last):
TransitionNotAllowed: Can't finish order when in Start.
>>> sm.order_value = 135.0
>>> sm.submit()
>>> …
```

feat: Comparison in condition expressions

---

README.md
conftest.py
docs/diagram.md
docs/transitions.md
tests/test_contrib_diagram.py

Using a new notebook, noted that the first run of the tests failed because the graphviz was missing. 
Turned these tests optional and skipped if the dot executable is not present.

tests: Ignore tests that requires dot if the executable is not present

---

docs/actions.md
docs/transitions.md
statemachine/event.py

I've been reading through the docs and found a couple of typos.

fix: typos

---

tests/scrape_images.py

Fix: Sanitise project path on windows for doc build
