- statemachine/statemachine.py
- tests/test_transitions.py
Fixes the issue when a transition is a combination of more than two transitions.
> Fix combined transitions can run with more than two transitions

- statemachine/statemachine.py
- tests/test_multiple_destinations.py
> Fixes #18: Callback can return destination state even if there's only one destination

- tests/test_multiple_destinations.py
Add a test to cover transition callback hook for multiple destination states returning a tuple:
Coverage should go to 100% 🎉 !
``` python
class ApprovalMachine(StateMachine):
"A workflow"
requested = State('Requested', initial=True)
accepted = State('Accepted')
denied = State('Denied')
@requested.to(accepted, denied)
def validate(self):
return 1, 2, self.accepted
machine = ApprovalMachine()
assert machine.validate() == (1, 2, )
```
> test(statemachine) Add test for multiple destinations returning as a tuple

- HISTORY.rst
- statemachine/statemachine.py
- tests/test_statemachine.py
- tests/test_statemachine_inheritance.py
PR based on #247.
Copy states and transitions from base classes.
TODO:
> Basic support for inheritance (based on #247)

- statemachine/statemachine.py
- tests/test_transitions.py
Fix returning dict as result of transitions callback. Closes #282
> fix: Fix returning dict as result of transitions callback. Closes #282

- HISTORY.rst
- docs/actions.md
- docs/conf.py
- docs/index.rst
- docs/transitions.rst
- pytest.ini
- requirements_test.txt
- setup.cfg
- statemachine/callbacks.py
- statemachine/exceptions.py
- statemachine/statemachine.py
- statemachine/utils.py
- tests/conftest.py
- tests/examples/traffic_light_machine.py
- tests/models.py
- tests/test_callbacks.py
- tests/test_multiple_destinations.py
- tests/test_state_callbacks.py
- tests/test_statemachine.py
- tests/test_statemachine_bounded_transitions.py
- tests/test_transitions.py
> [wip] feat: Actions structured

- README.rst
- docs/actions.md
- docs/index.rst
- docs/integrations.md
- docs/mixins.md
- docs/states.md
- docs/transitions.rst
- docs/usage.rst
- pytest.ini
- requirements_dev.txt
- requirements_test.txt
- statemachine/callbacks.py
- statemachine/mixins.py
- statemachine/statemachine.py
- tests/conftest.py
- tests/examples/order_control_machine.py
- tests/examples/traffic_light_machine.py
- tests/test_actions.py
- tests/test_callbacks.py
- tests/test_multiple_destinations.py
- tests/test_state_callbacks.py
- tests/test_statemachine.py
This PR formalizes the expected behavior of how actions and callbacks are performed.
- Closes: https://github.com/fgmacedo/python-statemachine/issues/295
- Closes https://github.com/fgmacedo/python-statemachine/issues/265
> Normalization of actions and callbacks

- README.rst
- docs/actions.md
- statemachine/callbacks.py
- statemachine/event.py
- statemachine/state.py
- statemachine/transition.py
- tests/test_actions.py
- tests/test_callbacks.py
Validators now implement the dynamic dispatch model.
Improved documentation about Actions and Guards.
> chore: Validators now implement the dynamic dispatch model

- statemachine/state.py
- statemachine/statemachine.py
- statemachine/transition.py
- tests/examples/order_control_rich_model_machine.py
- tests/test_callbacks_isolation.py
Fixes: https://github.com/fgmacedo/python-statemachine/issues/334 and https://github.com/fgmacedo/python-statemachine/issues/330
> hotfix: Fix a bug where the setup of callbacks was sharing data between instances due to the usage of property descriptors

- pyproject.toml
Signed-off-by: Schrotti <Schrott.Micha@web.de>
> fix missing version update to 1.0.3

- README.md
- docs/index.md
- docs/models.md
- docs/observers.md
- docs/releases/2.0.0.md
- docs/releases/index.md
Improved docs for the 2.0 release adding the backward incompatible changes.
> docs: Improved docs for 2.0 release

- poetry.lock
> chore: upgrading dependencies

- pyproject.toml
- tests/examples/persistent_model_machine.py
- tests/helpers.py
- tests/scrape_images.py
- tests/test_examples.py
New example of model based on #358.
> chore: New example of model

- .pre-commit-config.yaml
- conftest.py
- poetry.lock
- pyproject.toml
- statemachine/registry.py
- tests/conftest.py
- tests/django_project/app.py
- tests/django_project/conftest.py
- tests/django_project/core/settings.py
- tests/django_project/core/wsgi.py
- tests/django_project/manage.py
- tests/django_project/workflow/apps.py
- tests/django_project/workflow/models.py
- tests/django_project/workflow/statemachines.py
- tests/django_project/workflow/tests.py
- tests/test_registry.py
Adding Django to the tests pipeline so we can reproduce integration bugs easily.
Reproducing the error reported on https://github.com/fgmacedo/python-statemachine/issues/446
> tests: Adding Django test project

- statemachine/states.py
- tests/django_project/workflow/statemachines.py
- tests/examples/enum_campaign_machine.py
> fix: Regression on 2.3.2 that broke Enum support

- docs/releases/2.3.4.md
- docs/releases/index.md
- statemachine/callbacks.py
- statemachine/dispatcher.py
- statemachine/statemachine.py
- tests/test_listener.py
> fix: Regression that causes an exception when registering listeners with unbounded callables.

- .github/workflows/python-package.yml
- .github/workflows/release.yml
- docs/contributing.md
- poetry.lock
- pyproject.toml
Closes https://github.com/fgmacedo/python-statemachine/issues/474.
> fix: Extras [diagrams] to install pydot not working

- statemachine/engines/async_.py
- statemachine/engines/sync.py
- statemachine/statemachine.py
- tests/conftest.py
- tests/test_transitions.py
- tests/testcases/issue480.md
> fix: Fix #480, engine was not assigned on the initial callback

- docs/guards.md
- statemachine/callbacks.py
- statemachine/dispatcher.py
- statemachine/spec_parser.py
- tests/examples/lor_machine.py
- tests/test_conditions_algebra.py
- tests/test_spec_parser.py
Closes: https://github.com/fgmacedo/python-statemachine/issues/483
Allows boolean algebra to compound conditions (`cond` and `unless` clauses).
```py
from statemachine import State
from statemachine import StateMachine
class AnyConditionSM(StateMachine):
start = State(initial=True)
end = State(final=True)
submit = start.to(end, cond="used_money or used_credit")
used_money: bool = False
used_credit: bool = False
```
> feat: Conditionals with boolean algebra

- docs/api.md
- docs/transitions.md
- statemachine/__init__.py
- statemachine/dispatcher.py
- statemachine/event.py
- statemachine/events.py
- statemachine/factory.py
- statemachine/statemachine.py
- statemachine/transition.py
- statemachine/transition_list.py
- tests/test_events.py
Closes: https://github.com/fgmacedo/python-statemachine/issues/472
> feat: Improved Event class

- docs/async.md
> docs: Improving docs for async
